added travis CI; please check
athityakumar/tvseries pull request #38
Opened 2017-02-27 13:36 UTC by the-ethan-hunt

2017-02-27 13:44 UTC, athityakumar commented
I don't think that the above commit add Travis CI. Travis CI should be able to run the ruby script - to check whether the json building is successful or there are any errors.

2017-02-27 16:22 UTC, athityakumar commented
@the-ethan-hunt : BTW, you can also add `Gemlock` file to enable `bundle install` of gems and close issue #18

2017-03-09 09:05 UTC, the-ethan-hunt commented
@athityakumar Added Gemfile and Gemfile.lock. Sorry for the delay!

2017-03-09 11:51 UTC, athityakumar requested changes

2017-03-09 11:51 UTC, athityakumar commented on index.html
> +  //end of page
Is this change required? Revert this.

2017-03-09 11:54 UTC, athityakumar commented
@the-ethan-hunt - Thanks for adding Gemlock files! :smile: 

Travis CI hasn't been added yet - you can add them with `travis.yml` and `Rakefile.rb`. You can get help from this repository : https://github.com/barc-iitkgp/faculty-scraper

2017-03-12 05:57 UTC, the-ethan-hunt commented
updated index.hyml @athityakumar

2017-03-12 09:12 UTC, athityakumar commented
Thanks for the PR! Will you be adding Travis in the same PR or later?

2017-03-12 10:51 UTC, the-ethan-hunt commented
@athityakumar , CI generating error, will take some time..

2017-03-12 10:59 UTC, athityakumar commented
Oh, okay - I'll merge this then. Add another PR for CI.

2017-03-12 10:59 UTC, athityakumar approved these changes

2017-03-12 11:01 UTC, merged